repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1 # Usando a branch principal
    hooks:
      - id: isort
        args: ["--profile=black"] # Para alinhar com Black
  - repo: https://github.com/psf/black
    rev: 24.10.0 # Versão do Black
    hooks:
      - id: black
        args: ["--line-length=79"] # Limite de caracteres por linha
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=79
          - --extend-ignore=E501 # Ignore linhas muito longas (pois Black já ajusta)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.2
    hooks:
      - id: bandit
        args: ["--skip=B201,B113,B101"] # Pule checks problemáticos
  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: ["--remove-all-unused-imports", "--recursive", "--in-place"]
  - repo: local
    hooks:
      - id: run-tests
        name: "Run Python and JS tests"
        entry: ./scripts/run-tests.sh
        language: script
        files: ^codigo/tests/.*
