name: Continuous Integration (CI)

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Lint de JavaScript (ESLint)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23.3.0"

      - name: Install dependencies (Node.js)
        run: npm install

      - name: Run prettier for JavaScript
        run: npm run prettier:check

      # Lint de Python (Flake8)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install dependencies (Python)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit

      - name: Remove core.hooksPath if set
        run: git config --unset-all core.hooksPath

      - name: Install pre-commit hooks
        run: pre-commit install

      - name: Run Flake8 for Python
        run: pre-commit run --all-files

  unit_tests:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Rodando testes unitários de JavaScript (usando Jest ou Mocha)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23.3.0"

      - name: Install dependencies (Node.js)
        run: npm install

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install dependencies (Python)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests for JavaScript and Python
        run: npm test
