name: Roda API e Salva Json

on:
  schedule:
    - cron: '0 0 * * *'  # Executa o workflow uma vez por dia, às 00:00 UTC
  workflow_dispatch:  # Permite disparar manualmente o workflow se necessário

jobs:
  fetch_and_save_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          python actions/compras.py
          python actions/despesas_por_orgao.py
          python actions/bolsafamilia.py
        env:
          API_KEY: ${{ secrets.API_KEY }}  # Usa o secret API_KEY do GitHub
          API_COOKIE: ${{ secrets.API_COOKIE }}  # Referencia o secret do cookie

      - name: Show generated files
        run: |
          ls actions/json/  # Lista todos os arquivos gerados ou atualizados na pasta 'actions/json'

      - name: Check for changes in JSON files
        id: check_changes
        run: |
          # Verifica se houve alguma modificação nos arquivos JSON na pasta 'actions/json/'
          if git diff --exit-code actions/json/*.json; then
            echo "No changes in JSON files. Skipping commit."
            echo "::set-output name=files_changed::false"
          else
            echo "Changes detected in JSON files. Proceeding with commit."
            echo "::set-output name=files_changed::true"
          fi

      - name: Commit and push generated/updated JSON files
        if: steps.check_changes.outputs.files_changed == 'true'  # Só faz o commit se houver alterações nos arquivos JSON
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add actions/json/*.json  # Adiciona todos os arquivos JSON gerados ou atualizados na pasta 'actions/json'
          git commit -m "Update generated JSON files"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
