name: Roda API e Salva Json 2

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  fetch_and_save_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          python actions/bolsafamilia.py
          python actions/renuncias.py
        env:
          API_KEY: ${{ secrets.API_KEY }}  # Usa o secret API_KEY do GitHub
          API_COOKIE: ${{ secrets.API_COOKIE }}  # Referencia o secret do cookie

      - name: Show generated files
        run: |
          ls actions/json/  # Lista todos os arquivos gerados na pasta 'json'

      - name: Commit and push generated JSON files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add actions/json/*.json  # Adiciona todos os arquivos JSON gerados na pasta 'actions/json'
          git add actions/json/*.txt  # Adiciona todos os arquivos txt gerados na pasta 'actions/json'
          git commit -m "Add generated JSON files"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
