name: Fetch and Save Data from API

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite acionar o workflow manualmente a partir da interface do GitHub

jobs:
  fetch_and_save_data:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Configura o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Configura o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Rodar o script Python
      - name: Run Python script
        run: python despesas_por_orgao.py
        env:
          API_KEY: ${{ secrets.API_KEY }}  # Usa o secret API_KEY do GitHub
          API_COOKIE: ${{ secrets.API_COOKIE }}  # Referencia o secret do cookie

      # Passo 5: Mostrar os arquivos gerados (opcional)
      - name: Show generated files
        run: |
          ls despesas_json/  # Lista todos os arquivos gerados na pasta 'despesas_json'

      # Passo 6: Commit e Push dos arquivos gerados
      - name: Commit and push generated JSON files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add despesas_json/*.json  # Adiciona todos os arquivos JSON gerados na pasta 'despesas_json'
          git commit -m "Add generated JSON files"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
