name: Fetch API Data

on:
  schedule:
    # Executa o workflow diariamente às 4h da manhã (UTC)
    - cron: "0 4 * * *"
  workflow_dispatch: # Permite execução manual do workflow, se necessário

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Configura o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Configura o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Passo 3: Instala as dependências necessárias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Passo 4: Executa o script Python para obter os dados
      - name: Run fetch_data script
        run: python fetch_data.py

      # Passo 5: Comita e envia o arquivo atualizado
      - name: Commit and push updated data.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Update data.json [skip ci]"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
